#!/bin/sh

set -e
echo "Starting cibuild"
pwd
cd docs
pwd

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
#bundle exec script/validate-html
gem build jekyll-theme-byui-cs.gemspec

cd ..
pwd
